spring:
  application:
    name: web-api

  profiles:
    active: ${SPRING_PROFILES:local}

  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update